# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Megan Marshall
tagline:             'Personal Website'
description:         'My personal take on tech, design, and productivity.<br><a href="https://twitter.com/Mega5160" target="_blank">@Mega5160</a>.'
url:                 http://meganmarshall16.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Megan Marshall
  url:               https://twitter.com/mega5160
  email:             mega5160@gmail.com

# Custom vars
©:            2015. All rights reserved.

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'
